### ISSUE TITLE
Question : Possible to run mock server and my application on same port , to avoid CORS problems?

### ISSUE THREAD

**Issue by vishalksahu** [smollweide/node-mock-server#125]
My application runs on localhost:5000/ and  the node-mock-server on localhost:3001/

the outgoing calls are routed to  localhost:3001/items/active.

During this the browser complains of CORS Violation.

A workaround is to additionally have OPTION call in the mock responses, but this has be done for every call.

Thanks
Vishal

**Comment by smollweide** [comment]
Hi Vishal,
yes and no. You can use the expressMiddleware for it but there is no way to add the mock server to an existing express app. Maybe not a good idea because it’s a mock server build for mocking „external“ microservices / API‘s. The requirement you ask for means you are also the „owner“ of the server, which means you don’t need to mock it. Am I Right? Or did I miss a scenario where this makes sense?
 Thank you and have a nice day

**Comment by vishalksahu** [comment]
You got it right , It does not make good sense to do this in same port. 

For my problem with CORS Violation I could you one of the implementation of fallback (OPTIONS)  from your demo , so that I do not  have to do it everytime.

Thanks for the wonderful API
